spring:
  main:
    allow-circular-references: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: kiennkph42576@fpt.edu.vn
    password: zxnswhfbtzvvyfok
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
      mail.smtp.ssl.trust: smtp.gmail.com
    default-encoding: UTF-8

  datasource:
    url: jdbc:postgresql://localhost:5432/data_test
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:1}

  mvc:
    log-request-details: true

cloudinary:
  cloud-name: ${CLOUDINARY_CLOUD_NAME:dqowrxzgs}
  api-key: ${CLOUDINARY_API_KEY:976739115954629}
  api-secret: ${CLOUDINARY_API_SECRET:PNCF3TlvTFmaaoMIV1B0Z2ZNqYU}

logging:
  level:
    web: DEBUG
    org:
      springframework:
        web: DEBUG
      hibernate: ERROR
