server:
  port: 8080
  servlet:
    context-path: /api

spring:
  application:
    name: back_end
  profiles:
    active: dev
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB