spring:
  application:
    name: back_end

  datasource:
    url: jdbc:postgresql://localhost:5432/Store_DB
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:19082004}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    open-in-view: true
    properties:
      hibernate:
        globally_quoted_identifiers: true
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  sql:
    init:
      encoding: UTF-8

  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB

  main:
    allow-bean-definition-overriding: true

cloudinary:
  cloud-name: ${CLOUDINARY_CLOUD_NAME:dccuxj8ll}
  api-key: ${CLOUDINARY_API_KEY:934946519676845}
  api-secret: ${CLOUDINARY_API_SECRET:JORMLqc5oK1HzEPqS3toNumm5XI}
