server:
  port: 8080
  servlet:
    context-path: /api

spring:
  application:
    name: back_end
  profiles:
    active: dev
  file:
    upload-dir: I:/FPT POLYTECHNIC/DATN/CODE/18.3-DATN/back_end/src/main/java/com/example/back_end/imagelocal
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB